table artists
	lineageTag: 9ffa869a-7809-4740-b9d5-495a02058d2b

	column ArtistId
		dataType: int64
		formatString: 0
		lineageTag: 6dbceb65-0fd7-4d47-bd93-5c1f1121f17c
		summarizeBy: none
		sourceColumn: ArtistId

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 908f1c35-321f-4bb0-9b89-ba84660cc37c
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition artists = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\HP\Downloads\artists.csv"),[Delimiter="	", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ArtistId", Int64.Type}, {"Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

